### ISSUE TITLE
Games crashes on launch with "Failed to compile shaders" assert

### ISSUE THREAD

**Issue by KrystianRozwag** [deathkiller/jazz2#135]
Hi there, I tried to check your project and build the solution by using VS2022. I downloaded the solution with dependencies and it compiles fine (besides I need to move the dll files to the debug directory, so it does not complain about them), but when I try to launch the game it asserts on "Failed to compile shader" assert. There is something wrong while building the .exe file, because when I replaced mine with yours provided to just play the game, everything ran fine, but I couldn't debug the game. I'm kind of novice in the topic and I chose your project to learn :D I hope, we will be able to solve this issue.

**Comment by deathkiller** [comment]
Hi, if you open the project using SLN, it requires `Sources\nCine\Shaders\` directory to be copied to `Content\Shaders\` in your game directory. I would recommend to open the project using CMake instead, the directory is not necessary then (that's why my EXE works) and it should copy everything automatically. The SLN file is used only by me locally.

**Comment by KrystianRozwag** [comment]
Thank you! It works now :)
