### ISSUE TITLE
Some ES2.0 shaders are missing?

### ISSUE THREAD

**Issue by chewi** [deathkiller/jazz2#25]
I did struggle to get ES2.0 working in my Gentoo package at all and nearly gave up. I'm closer now with the menu being visible but when I try to start the game, it says `Shaders\TransitionSmooth.res` is missing. I can see this was added to the main shaders more recently but it is missing from the `_ES20/Shaders` directory.

**Comment by deathkiller** [comment]
You are right, sorry. I thought nobody uses ES 2.0 😀 In WebAssembly, there is backend that translates ES 3.0 shaders to WebGL 1.0 shaders. So it would be probably better option to implement it in ES 2.0 backend too. But ES2.0 is not recommended, because it does not support Multi Render Targets which is used for lighting. Anyway, I will fix it soon.

**Comment by chewi** [comment]
I wasn't planning to use it myself but Gentoo is used for all kinds of exotic hardware, some with limited GL capabilities, so we like to offer the option where it's feasible. Thanks for fixing. 🙂

**Comment by deathkiller** [comment]
Fixed, but not tested. I don't have working ES20 drivers right now.

**Comment by chewi** [comment]
I'll test ASAP. Also don't release yet, I have some changes of my own coming!

**Comment by deathkiller** [comment]
I have some multiplayer features in development, so new version is not going to be released this week anyway. 😊

**Comment by chewi** [comment]
I can now confirm it works!

**Comment by deathkiller** [comment]
Great, thanks.
