### ISSUE TITLE
failing to compile shaders on  RPI4

### ISSUE THREAD

**Issue by Askmewho** [deathkiller/jazz2#29]
Hi, So, Ive tested your remake on RPI4 ( Ive just to replace the libopenmpt.so to launch) but it failt to compile shaders. While this game should run on opengl 2.1 desktop (profile than we have) I asume it have a compression format than the pi gpu cant handle. Ive tried gl4es (I dont think it was related to s3tc by any means, but just a lucky shot), and it dows not work neither. thanks on advance

**Comment by deathkiller** [comment]
Hi,
do you have log file (`Jazz2.log` or probably `~/.local/share/Jazz2/Jazz2.log`)?

**Comment by Askmewho** [comment]
Ive couldnt find it, but just for an start, this is my output. 
[out.txt](https://github.com/deathkiller/jazz2/files/4111927/out.txt)

**Comment by Askmewho** [comment]
couldnt find it, this is my output...
[jazz.txt](https://github.com/deathkiller/jazz2/files/4111936/jazz.txt)

**Comment by deathkiller** [comment]
Yes, this is the log. It uses terminal instead of file if there is one.

However, `Failed to register allocate at 2 threads` and `fragment shader failed to compile. Expect corruption.` messages don't come from the game, so maybe it's the driver. The game should write shader compilation log, but it's not present in the log. It seems the game crashed because of the driver. Can you try to turn on some better logging in the driver? I don't have any experience with mesa driver.

**Comment by Askmewho** [comment]
Yeah, I could make some debugging on shaders, bc it could be useful for mesa devs.

**Comment by deathkiller** [comment]
Closed due to inactivity.
