### ISSUE TITLE
Controller bindings detect incorrect buttons

### ISSUE THREAD

**Issue by MavisCelus19201** [deathkiller/jazz2#53]
When I try remapping with a controller, it inputs the wrong butons, so B is registered as the down input, clicking on the left thumbstick is registered as the A button, and the triggers aren't detected at all, just to name a few examples, keyboard bindings work as they should but not controller.

This is via the Linux 0.67 build using an Afterglow Prismatic Xbox One controller, so I'm unsure if this is the case with other gamepads since I don't have any others to test.

**Comment by deathkiller** [comment]
Triggers and analog sticks cannot be remapped (triggers cannot be mapped at all, it's not supported by the game), so that's why it's not detected. The game uses OpenTK library for input and OpenTK uses XInput on Windows, so I don't know how it's implemented on Linux. OpenTK issues are really hard to fix for me.

**Comment by deathkiller** [comment]
This should be fixed in new C++ version, so this will not be resolved in this C# version.

**Comment by coreybruce** [comment]
Have the same issue with the xbox one controller binding the incorrect buttons, it thinks the X,Y,B and A buttons are directional buttons and the rest of the controller doesn't work due to this issue.
