### ISSUE TITLE
Question: Is persisted data for imported data planned for easier updates?

### ISSUE THREAD

**Issue by RavenMacDaddy** [deathkiller/jazz2#81]
I'm currently creating a manifest for the CLI [Scoop](https://scoop.sh/), so this question came to mind.

Of course I read your answer [here](http://deat.tk/jazz2/help), but for the purposes I'd greatly appreciate your take.

**Comment by deathkiller** [comment]
I'm not sure I understand your question, but in latest versions imported data don't change that much. I'm rewritting the game to C++ and planning to remove import process entirely. I can't do much about it until then.

**Comment by RavenMacDaddy** [comment]
Well, that would solve the problem at hand - thank you for your work.

**Comment by deathkiller** [comment]
`Main.dz` contains all shared game data and problem is it's connected to each version - that's why I usually give a warning that you should delete the previous one and re-import with the new one. The only file that is safe after update is `Jazz2.settings`.

I'm planning to implement automatic re-importing, so the game automatically detects that something changed and do it automatically, but it's not done yet.

**Comment by RavenMacDaddy** [comment]
> I'm planning to implement automatic re-importing, so the game automatically detects that something changed and do it automatically, but it's not done yet.

So, would that re-import from the same directory that was used last time, or do you have that part figured out? Would you mind elaborating?

**Comment by deathkiller** [comment]
I don't know yet. I thought original JJ2 will be in hardcoded subdirectory, but I'm affraid it might not be enough.

**Comment by RavenMacDaddy** [comment]
If it's possible it would be very easy to persist at least. 

Fingers crossed you manage to figure it out.

**Comment by deathkiller** [comment]
This has been implemented in new C++ version, so this will not be resolved in this C# version.
